* Fodsearch API
The fodmap ingredient API.
** About
Information about low fodmap ingredients are scattered about the web, in plain text, images, web apps, etc. This API is an effort to put all low fodmap ingredients into a single place to make them easier to find.

This is a work in progress!
** Endpoints
*** Health
**** GET =/api/v1/health=
A health check (this should return true!)
#+begin_src sh
curl "http://localhost:3000/api/ingredients"
#+end_src
*** Ingredients
**** GET =/api/v1/ingredients=
Get list of all ingredients.
#+begin_src sh
curl "http://localhost:3000/api/ingredients"
#+end_src
**** GET =/api/v1/ingredients?q=melon=
Search for ingredients that match the query =q=
#+begin_src sh
curl "http://localhost:3000/api/ingredients?q=melon"
#+end_src
**** GET =/api/v1/ingredients/:ingredient-id=
Get a single ingredient by its id.
#+begin_src sh
curl "http://localhost:3000/api/ingredients/1"
#+end_src
**** DELETE =/api/v1/ingredients/:ingredient-id=
Delete a single ingredient by its id.
#+begin_src sh
curl -X DELETE "http://localhost:3000/api/ingredients/1"
#+end_src
**** POST =/api/v1/ingredients=
Create a single ingredient.
#+begin_src sh
curl -X POST -d '{"name": "Test Ingredient", "info": "none", "level":"moderate","category":"fruit"}' "http://localhost:3000/api/ingredients"
#+end_src
**** PUT =/api/v1/ingredients/1=
Update a single ingredient by its id.
#+begin_src sh
curl -X POST -d '{"name": "Better Alfalfa", "info": "none", "level":"moderate","category":"fruit"}' "http://localhost:3000/api/ingredients/1"
#+end_src
The given =level= and =category= need to exist for this to be successful.
*** Levels
**** GET =/api/v1/levels=
Get a list of all levels.
#+begin_src sh
curl "http://localhost:3000/api/levels"
#+end_src
**** GET =/api/v1/levels/:level-id=
Get a single category by its id.
#+begin_src sh
curl "http://localhost:3000/api/levels/1"
#+end_src
**** POST =/api/v1/levels=
Create a single level.
#+begin_src sh
curl -X POST -d '{"name": "Test Level"}' "http://localhost:3000/api/levels"
#+end_src
**** PUT =/api/v1/levels/1=
Update a single level by its id.
#+begin_src sh
curl -X POST -d '{"name": "unsafe"}' "http://localhost:3000/api/levels/1"
#+end_src
**** DELETE =/api/v1/ingredients/:level-id=
Delete a single level by its id.
#+begin_src sh
curl -X DELETE "http://localhost:3000/api/level/1"
#+end_src
This will not work if the level is being used by an ingredient.
*** Categories
**** GET =/api/v1/categories=
Get a list of all categories.
#+begin_src sh
curl "http://localhost:3000/api/categories"
#+end_src
**** GET =/api/v1/categories/:category-id=
Get a single category by its id.
#+begin_src sh
curl "http://localhost:3000/api/categories/1"
#+end_src
**** POST =/api/v1/categories=
Create a single category.
#+begin_src sh
curl -X POST -d '{"name": "Test Category"}' "http://localhost:3000/api/categories"
#+end_src
**** PUT =/api/v1/categories/1=
Update a single category by its id.
#+begin_src sh
curl -X POST -d '{"name": "veggies"}' "http://localhost:3000/api/levels/1"
#+end_src
**** DELETE =/api/v1/categories/:category-id=
Delete a single category by its id.
#+begin_src sh
curl -X DELETE "http://localhost:3000/api/categories/1"
#+end_src
This will not work if the category is being used by an ingredient.
